#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

ideasUnvToFoam *.unv
transformPoints scale="(0.001 0.001 0.001)"
splitMeshRegions -cellZones -overwrite


paraFoam -touch -region fluid
paraFoam -touch -region heater
paraFoam -touch -region fins
#------------------------------------------------------------------------------
