#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

runApplication -s fluid    decomposePar -region fluid
runApplication -s heater decomposePar -region heater
runApplication -s fins decomposePar -region fins

runParallel $(getApplication)

runApplication -s fluid    reconstructPar -region fluid
runApplication -s fins reconstructPar -region fins
runApplication -s heater reconstructPar -region heater
