#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create meshes
ideasUnvToFoam mesh.unv
splitMeshRegions -cellZones -overwrite
transformPoints scale='(0.001 0.001 0.001)'

# Create rotor blades in air region
# runApplication -s air.1 topoSet -region air -dict topoSetDict.1
# runApplication createBaffles -region air -overwrite

# Create rotor zone in air region for MRF
# runApplication -s air.2 topoSet -region air -dict topoSetDict.2

rm -rf constant/air/polyMesh/sets

# Create dummy files for post-processing
paraFoam -touch -region fluid
paraFoam -touch -region heater
paraFoam -touch -region fins

#------------------------------------------------------------------------------
